        insert into item (itemid,name) values (0,"Belleze 48" Rectangular Faux Leather Linen Storage Ottoman Bench Footrest, Large Space");"
        insert into item (itemid,name) values (0,"Rockpoint Plymouth Wood TV Stand Storage Console");
        insert into item (itemid,name) values (0,"Convenience Concepts Designs4Comfort Storage Ottoman");
        insert into item (itemid,name) values (0,"Olee Sleep Solid Wood &amp; Dura Metal Legs Sofa Table");
        insert into item (itemid,name) values (0,"Monarch Specialties Accent Table - 47" L/Hall Console");"
        insert into item (itemid,name) values (0,"Convenience Concepts Tucson Electric Flip Top Table");
        insert into item (itemid,name) values (0,"SONGMICS Ladder Shelf");
        insert into item (itemid,name) values (0,"Casual Home 176-51 5-Shelf Ladder Bookcase");
        insert into item (itemid,name) values (0,"Winsome Timmy Accent Table, Black");
        insert into item (itemid,name) values (0,"Convenience Concepts American Heritage Flip Top End Table, Black");
        insert into item (itemid,name) values (0,"Convenience Concepts Tucson Collection Console Table");
        insert into item (itemid,name) values (0,"Convenience Concepts Oxford Console Table");
        insert into item (itemid,name) values (0,"SONGMICS 43" L Folding Storage Ottoman Bench with Flipping Lid, Storage Chest/Footrest/Padded Seat with Iron Frame Support");
        insert into item (itemid,name) values (0,"Nathan James Doxa Solid Wood Modern Industrial Coffee Table");
        insert into item (itemid,name) values (0,"Casual Home 660-40 5 Piece Tray Table Set, Natural");
        insert into item (itemid,name) values (0,"Prepac Media Storage Cabinet");
        insert into item (itemid,name) values (0,"HOMEMAXS Sofa Side End Table C Table Multiple Stand 26-Inch for Small Space New");
        insert into item (itemid,name) values (0,"Elite Cuisine Watt Hand Blender with One Touch Button");
        insert into item (itemid,name) values (0,"MAGIC UNION Wood End Table With drawer");
        insert into item (itemid,name) values (0,"SONGMICS Folding Storage Ottoman Coffee Table Foot Rest Stool, Faux Leather,");
        insert into item (itemid,name) values (0,"SONGMICS Folding Storage Ottoman Bench with Flipping Lid, Storage Chest Footstool Coffee Table");
        insert into item (itemid,name) values (0,"Convenience Concepts Oxford End Table");
        insert into item (itemid,name) values (0,"Crown Mark Pierce Side Table");
        insert into item (itemid,name) values (0,"Otto &amp; Ben 30" Storage Ottoman with SMART LIFT Top, Folding Foot Rest Stools Table Ottomans Bench with Linen Fabric, Parent");"
        insert into item (itemid,name) values (0,"Winsome Wood End Table/Night Stand with Drawer and Shelf");
        insert into item (itemid,name) values (0,"RoomDividersNow Premium Heavyweight Room Divider Curtains, 8ft - 9ft Tall x 5ft - 15ft Wide Panels");
        insert into item (itemid,name) values (0,"DHP Rosewood Tall, Simple Design, Multi-purpose Small Space Table, Medium Coffee Brown");
        insert into item (itemid,name) values (0,"Nathan James Theo Wood Ladder Bookshelf");
        insert into item (itemid,name) values (0,"Furinno 12127CWN/BK Turn-S-Tube End Table 2-Pack, Columbia Walnut/Black");
        insert into item (itemid,name) values (0,"TomCare Cube Storage");
        insert into item (itemid,name) values (0,"Sorbus Storage Ottoman Bench – Collapsible/Folding Bench Chest with Cover – Perfect Toy and Shoe Chest, Hope Chest, Pouffe Ottoman, Seat, Foot Rest, – Contemporary Faux Suede");
        insert into item (itemid,name) values (0,"Storage Dynamics JB6032 Slide Out Storage Tower");
        insert into item (itemid,name) values (0,"Furinno 11157CWN/DBR Andrey Bin Drawer End Table, 1, Columbia Walnut/Dark Brown");
        insert into item (itemid,name) values (0,"Furinno 2-99800BRM Turn-N-Tube Haydn 2-Pack End Table, Faux Marble/Brown");
        insert into item (itemid,name) values (0,"DHP 3537496 Parsons Coffee Table");
        insert into item (itemid,name) values (0,"Otto &amp; Ben 45" Storage Ottoman with Memory Foam Seat, Folding Large Foot Rest");"
        insert into item (itemid,name) values (0,"Ashley Furniture Signature Design - Laflorn Chairside End Table - Rectangular");
        insert into item (itemid,name) values (0,"Furinno");
        insert into item (itemid,name) values (0,"XOWRTE Women's Plus Size Solid Color Autumn Long Sleeve T-Shirt Tunic Blouse Tops");
        insert into item (itemid,name) values (0,"Homegear Modern Door/Wall Mounted Mirrored Jewelry Cabinet Organizer Storage");
        insert into item (itemid,name) values (0,"4-Panel Folding Screen Black and White");
        insert into item (itemid,name) values (0,"Child Craft Shoal Creek Storage Chest/Toy Chest, White");
        insert into item (itemid,name) values (0,"SONGMICS Vintage Nightstand, Stackable End Table, Cabinet for Storage, Side Table for Small Spaces, Wood Look Accent Furniture Metal Frame ULET54X");
        insert into item (itemid,name) values (0,"SONGMICS Mobile Snack Table Sofa Side Table");
        insert into item (itemid,name) values (0,"Sauder Caraway Floor Cabinet in soft white");
        insert into item (itemid,name) values (0,"Zinus Modern Studio Collection 20 Inch Square Side / End Table / Night Stand / Coffee Table, Espresso");
        insert into item (itemid,name) values (0,"Zinus Modern Studio Collection 20 Inch Square Side / End Table / Night Stand / Coffee Table, Brown");
        insert into item (itemid,name) values (0,"Seville Classics WEB558 Faux Leather Quilted Foldable Storage Ottoman");
        insert into item (itemid,name) values (0,"Mouttop Advent Calendar Made with Pandora DIY Beads Charms Bracelet for Kids Christmas Jewelry Box, Silver");
        insert into item (itemid,name) values (0,"Holiday Advent Calendar Chocolates for Christmas, 24 Chocolate Days til' Christmas, Countdown Chocolate Calendar for Kids, Season Treats, Gift Ideas");
        insert into item (itemid,name) values (0,"Naughty or Nice Chocolate Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"Smiling Shepherds Chocolate Advent Calendar &amp; Nativity Story");
        insert into item (itemid,name) values (0,"Alleluia Chocolate Advent Calendar");
        insert into item (itemid,name) values (0,"DII Large Hanging");
        insert into item (itemid,name) values (0,"Clever Creations Wooden Advent Calendar | Bright Lights and Christmas Cheer | Perfect Decorations for Your Home");
        insert into item (itemid,name) values (0,"Spirit of Christmas Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"Juegoal Countdown to Christmas Nature Wood Advent Calendar with 24 Storage Drawers Decoration, 12" Tall");"
        insert into item (itemid,name) values (0,"Mouttop Advent Calendar,Charm Bracelet DIY 23Charms with 1 Bracelet Fashion Jewelry Christams Advent Calendars for Kids(2018 Pink)");
        insert into item (itemid,name) values (0,"Unomor Wooden Advent Calendar for Kids with 31 Magnets, Countdown to Magnetic Christmas Advent Calendar Tree");
        insert into item (itemid,name) values (0,"Christmas Tree Countdown Advent Calendar, Filled with Solid Premium Milk Chocolate Presents");
        insert into item (itemid,name) values (0,"Purple Ladybug Novelty Mochi Squishy 2018 Advent Calendar for Kids - 3 Editions - Santa's Sleigh, Santa's Workshop, Santa and The Tree");
        insert into item (itemid,name) values (0,"SWEET DIARY Christmas Advent Calendar 2018 Tabletop Christmas Tree Countdown Calendar 24 Days, 23.6" Pine Tree Kids Boys Girl Xmas Gifts DIY Christmas Ornaments 23 Toy Home Office Desk Decorations");"
        insert into item (itemid,name) values (0,"Disney TSUM TSUM Advent Calendar");
        insert into item (itemid,name) values (0,"Wooden Gingerbread House Countdown to Christmas Advent Calendar 10.5 x 8 x 9.5 H");
        insert into item (itemid,name) values (0,"Hot Wheels Advent Calendar");
        insert into item (itemid,name) values (0,"Tidings of Joy Fabric Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"Nativity Fabric Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"SAND MINE Countdown to Christmas Wooden Advent Calendar");
        insert into item (itemid,name) values (0,"Crayola Christmas Countdown Activity Advent Calendar");
        insert into item (itemid,name) values (0,"Lindt Teddy Bear Christmas Countdown Advent Calender 128 g");
        insert into item (itemid,name) values (0,"Frozen Disney Olaf's Adventure Advent Calendar");
        insert into item (itemid,name) values (0,"D-FantiX Christmas Countdown Calendar Women Girls Jewelry Advent Calendar 2018 DIY 24 Days Charms with Bracelet Emoji Beads Ear Studs Set");
        insert into item (itemid,name) values (0,"Juegoal Countdown to Christmas Calendar Nature Wood Tree Shape Advent Calendar 24 Storage Drawers, 15" Tall");"
        insert into item (itemid,name) values (0,"TrendWind Advent Calendar 2018 Fashion Bracelet with 22 Charms Countdown Christmas Gifts for Kids,Mat Silver");
        insert into item (itemid,name) values (0,"O Christmas Tree Treasure Box Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"Mouttop 24 Days Christmas Advent Calendar Fashion Jewelry 22 Charms 1 Bracelet 1 Necklace, Red");
        insert into item (itemid,name) values (0,"D-FantiX 3D Santa Felt Advent Calendar 2018 Countdown to Christmas Calendar Indoor Christmas Decorations, Red and White");
        insert into item (itemid,name) values (0,"Melissa &amp; Doug Countdown to Christmas Wooden Advent Calendar - Magnetic Tree, 25 Magnets");
        insert into item (itemid,name) values (0,"Advent Calendar (HARIBO) 300g");
        insert into item (itemid,name) values (0,"Advent Calendar Countdown to Christmas with DIY Pandora Beads Charms Jewelry Bracelet Set");
        insert into item (itemid,name) values (0,"Advent Calendar for Alcohol &amp; Adults | Gift Booze for Christmas 2018 | Great White Elephant &amp; Holiday Party Hostess Present Idea");
        insert into item (itemid,name) values (0,"Woodland Skaters Chocolate Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"24 Chocolate Days till Christmas Advent Calendar Pack (2 in each pack) (Santas Coming to Town Pack)");
        insert into item (itemid,name) values (0,"Whistle Stop Christmas Chocolate Advent Calendar Filled With 24 Milk Chocolates(2.65 oz)");
        insert into item (itemid,name) values (0,"Vermont Christmas Company Ready Reindeer Chocolate Advent Calendar");
        insert into item (itemid,name) values (0,"Holiday Village Square Chocolate Advent Calendar (Countdown to Christmas Calendar)");
        insert into item (itemid,name) values (0,"Christmas Eve Chocolate Advent Calendar (Countdown to Christmas Calendar)");
        insert into item (itemid,name) values (0,"Snowman Celebration Chocolate Advent Calendar (Countdown to Christmas),2.65 OZ");
        insert into item (itemid,name) values (0,"Advent Calendar - Nativity Scene (Special Chocolate Series)");
        insert into item (itemid,name) values (0,"Trolls DreamWorks Holiday Countdown Advent Calendar");
        insert into item (itemid,name) values (0,"Visiting the Manger Free Standing Advent Calendar");
        insert into item (itemid,name) values (0,"Christmas Feast Chocolate Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"Elf Magic Advent Calendar");
        insert into item (itemid,name) values (0,"Stained Glass Nativity Advent Calendar (Christmas Countdown Calendar)");
        insert into item (itemid,name) values (0,"Following the Star Advent Calendar with Nativity Story");
        insert into item (itemid,name) values (0,"Christmas in Town Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"Christmas Cheer Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"Canine Christmas Tree Advent Calendar (Countdown to Christmas)");
        insert into item (itemid,name) values (0,"CoverMates Window Air Conditioner Cover");
